In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [14]:
dataset=load_iris()


In [15]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [17]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [18]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [19]:
df['target']=dataset.target

In [20]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                  5.1               3.5                1.4               0.2  \
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [21]:
#making binary by drop 2
df_copy=df[df['target']!=2]

In [22]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                 5.1               3.5                1.4               0.2  \
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [28]:
#distribution off data

X=df_copy.iloc[:,:-1]
Y=df_copy.iloc[:,-1]

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [32]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
55                5.7               2.8                4.5               1.3
88                5.6               3.0                4.1               1.3
26                5.0               3.4                1.6               0.4
42                4.4               3.2                1.3               0.2
69                5.6               2.5                3.9               1.1
..                ...               ...                ...               ...
60                5.0               2.0                3.5               1.0
71                6.1               2.8                4.0               1.3
14                5.8               4.0                1.2               0.2
92                5.8               2.6                4.0               1.2
51                6.4               3.2                4.5               1.5

[80 rows x 4 columns]

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
classification=LogisticRegression()

In [35]:
classification.fit(X_train,y_train)

LogisticRegression()

In [37]:
y_pred=classification.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [40]:
confusion_matrix(y_test,y_pred)

array([[12,  0],
       [ 0,  8]], dtype=int64)

In [41]:
accuracy_score(y_test,y_pred)

1.0

In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [45]:
#Hyper Parameter Tuning

from sklearn.model_selection import KFold

In [46]:
cv=KFold(n_splits=5)

In [47]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [48]:
from sklearn.model_selection import cross_val_score

In [50]:
score=cross_val_score(classification,X_train,y_train,scoring='accuracy',cv=cv)

In [51]:
np.mean(score)

1.0

# classification,make_classification

In [52]:
from sklearn.datasets import make_classification

In [54]:
from sklearn.linear_model import LogisticRegression

In [57]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=5,
    n_redundant=5,
    n_classes=2,random_state=1)

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [60]:
complex_classification=LogisticRegression()

In [61]:
complex_classification.fit(X_train,y_train)

LogisticRegression()

In [64]:
y_pred=complex_classification.predict(X_test)

In [65]:
accuracy_score(y_test,y_pred)

0.79

In [66]:
confusion_matrix(y_test,y_pred)

array([[78, 13],
       [29, 80]], dtype=int64)

In [67]:
score=cross_val_score(complex_classification,X_train,y_train,scoring='accuracy',cv=cv)

In [68]:
score

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [69]:
from sklearn.model_selection import GridSearchCV

In [76]:
parameters=({'penalty':('l1', 'l2', 'elasticnet'),'C':[1,10,15,20]})
grid=GridSearchCV(complex_classification,param_grid=parameters,cv=5)
grid.fit(X_train,y_train)

C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
40 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 15, 20],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [77]:
grid.best_params_

{'C': 1, 'penalty': 'l2'}

In [78]:
grid.best_score_

0.8087500000000001

In [79]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [80]:
# define the multinomial logistic regression model For multiclass classification
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [81]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [82]:
# trianing model
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [84]:
y_pred=model.predict(X_test)

In [85]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[56 10 17]
 [16 41  6]
 [ 3 13 38]]
0.675
              precision    recall  f1-score   support

           0       0.75      0.67      0.71        83
           1       0.64      0.65      0.65        63
           2       0.62      0.70      0.66        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200

